version: '3'

services:
  xwindow:
    image: busybox
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ~/.Xauthority:/root/.Xauthority:rw
      - /tmp/.docker.$USER.xauth:/tmp/.docker.xauth:ro
  yolo:
    shm_size: '8gb'
    image: yolo/pytorch:1.7.0-cuda11.2.2-cudnn8-runtime
    network_mode: "host"
    container_name: yolo
    tty: true

    runtime: nvidia
    group_add:
      - video
    environment:
      - MESA_GL_VERSION_OVERRIDE=4.2
      - XAUTHORITY=/tmp/.docker.xauth
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - ~/share:/root/share:rw
    volumes_from:
      - xwindow
    command: /bin/bash
